<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-NO0KCPB3" failures="1" tests="8" name="testCases.QALegendTestCases" time="126.678" errors="0" timestamp="2024-02-22T19:49:25 IST" skipped="0">
  <testcase classname="testCases.QALegendTestCases" name="applyLeave" time="12.552"/>
  <testcase classname="testCases.QALegendTestCases" name="addTickets" time="16.910">
    <failure message="expected:&lt;73&gt; but was:&lt;74&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<73> but was:<74>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at testCases.QALegendTestCases.addTickets(QALegendTestCases.java:329)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- addTickets -->
  <testcase classname="testCases.QALegendTestCases" name="addAnnouncements" time="13.251"/>
  <testcase classname="testCases.QALegendTestCases" name="addAnnouncements" time="16.562"/>
  <testcase classname="testCases.QALegendTestCases" name="addTickets" time="20.978"/>
  <testcase classname="testCases.QALegendTestCases" name="addInvoice" time="14.641"/>
  <testcase classname="testCases.QALegendTestCases" name="addInvoice" time="19.988"/>
  <testcase classname="testCases.QALegendTestCases" name="applyLeave" time="11.796"/>
</testsuite> <!-- testCases.QALegendTestCases -->
